#!/bin/bash - 
root=$DOTFILES_ROOT
if [[ ! -d ~/.spacemacs.d ]]; then
	mkdir ~/.spacemacs.d
fi
ln -sif $root/config_spacemacs/init.el ~/.spacemacs.d/init.el
if [[ ! -L ~/.spacemacs.d/config ]]; then
	ln -sif $root/config_spacemacs/config ~/.spacemacs.d/config
fi

private_layers=(dmx dmx-lua)
for (( i = 0; i < ${#private_layers[@]}; i++ )); do
	p_layername=${private_layers[i]}
	if [[ ! -L ~/.emacs.d/private/${p_layername} ]]; then
		ln -sif $root/config_spacemacs/private/${p_layername} ~/.emacs.d/private/${p_layername}
	fi
done

if [[ -d ~/.emacs.d/private/snippets ]]; then
	rm -rf ~/.emacs.d/private/snippets
	ln -sif $root/config_spacemacs/private/snippets ~/.emacs.d/private/snippets
fi
