#!/bin/bash - 
root=$DOTFILES_ROOT
if [[ ! -d ~/.spacemacs.d ]]; then
	mkdir ~/.spacemacs.d
fi
ln -sif $root/config_spacemacs/init.el ~/.spacemacs.d/init.el
if [[ ! -L ~/.spacemacs.d/config ]]; then
	ln -sif $root/config_spacemacs/config ~/.spacemacs.d/config
fi

if [[ ! -L ~/.emacs.d/private/dmx ]]; then
	ln -sif $root/config_spacemacs/private_layers/dmx ~/.emacs.d/private/dmx
fi
