#!/bin/bash - 
#===============================================================================
#
#          FILE: dp_ctags.sh
# 
#         USAGE: ./dp_ctags.sh 
# 
#   DESCRIPTION: 
# 
#       OPTIONS: ---
#  REQUIREMENTS: ---
#          BUGS: ---
#         NOTES: ---
#        AUTHOR: dingmingxin (dmx), dignmingxin20@gmail.com
#  ORGANIZATION: 
#       CREATED: 10/30/2014 18:00
#      REVISION:  ---
#===============================================================================

ln -isf ~/dotfiles/config_ctags ~/.config_ctags

