#!/bin/bash - 
#===============================================================================
#
#          FILE: dpwiki.sh
# 
#         USAGE: ./dpwiki.sh 
# 
#   DESCRIPTION: 
# 
#       OPTIONS: ---
#  REQUIREMENTS: ---
#          BUGS: ---
#         NOTES: ---
#        AUTHOR: dingmingxin (dmx), dignmingxin20@gmail.com
#  ORGANIZATION: 
#       CREATED: 10/27/2014 19:38
#      REVISION:  ---
#===============================================================================

ln -isf ~/dotfiles/wiki ~/wiki

