#!/bin/bash - 
#===============================================================================
#
#          FILE: terminalInit.sh
# 
#         USAGE: ./terminalInit.sh 
# 
#   DESCRIPTION: 
# 
#       OPTIONS: ---
#  REQUIREMENTS: ---
#          BUGS: ---
#         NOTES: ---
#        AUTHOR: dingmingxin (dmx), dignmingxin20@gmail.com
#  ORGANIZATION: 
#       CREATED: 10/20/2014 14:43
#      REVISION:  ---
#===============================================================================
which tmux > /dev/null
if [[  ! $? -eq 0 ]]; then
	echo "tmux command not found"
	echo "please 'sudo port install tmux'"
	return
fi
which mux > /dev/null
if [[  ! $? -eq 0 ]]; then
	echo "mux command not found"
	echo "please 'sudo gem install tmuxinator'"
	return
fi
tmux start-server
wait
need_sessions=(
	'test'
	'todo'
	'dotfiles'
	'sanguo2'
)
need_start_num=0
cur_sessions=$(tmux ls |awk -F: '{print $1}')
for nsname in ${need_sessions[@]}
do
	tmux has-session -t $nsname
	if [[ $? -eq 0 ]]; then
		continue
	fi
	(( need_start_num=$need_start_num+1 ))
	(
	mux start $nsname > /dev/null 2>&1 &
	)
done
if [[ ! $need_start_num -eq 0 ]]; then
	mux start sanguo2
else
	echo "all tmux sessions started"
fi
