#!/bin/bash
# .bashrc
#share command history with different bash ttys
export HISTCONTROL=ignoredups
export HISTIGNORE="[   ]*:&:bg:fg:exit:pwd:ls:ll:history"
export HISTFILESIZE=1000000000
export HISTSIZE=1000000
export HISTTIMEFORMAT='%F %T '
shopt -s histappend
export DISPLAY=:0
export EDITOR=vim
export HISTSIZE=1000000
export GIT_SSL_NO_VERIFY=true
#set ls command color
export CLICOLOR="xterm-color"
# export LSCOLORS=Ehfxcxdxbxegedabagacad
export LSCOLORS=ExFxCxDxbxegedabagacad
export GREP_OPTIONS="--color=auto"

SOURCE_FILES=(
	/opt/local/etc/bash_completion \
	~/.git-completion.bash \
	/etc/git-completion.bash \
	~/.git-prompt.sh \
	~/.bash_prompt \
	~/.bash_aliases \
	~/.bash_path)

for file in ${SOURCE_FILES[@]}
do
	[[ -f $file ]] && . $file
done
