#!/bin/bash
# .bashrc
#share command history with different bash ttys
export HISTCONTROL=ignoredups
export HISTIGNORE="[   ]*:&:bg:fg:exit"
export HISTFILESIZE=1000000000
export HISTSIZE=1000000
shopt -s histappend
export DISPLAY=:0
export EDITOR=vim
export HISTSIZE=1000000
export GIT_SSL_NO_VERIFY=true
#set ls command color
export CLICOLOR="xterm-color"
# export LSCOLORS=Ehfxcxdxbxegedabagacad
export LSCOLORS=ExFxCxDxbxegedabagacad
export GREP_OPTIONS="--color=auto"

if [ -f /opt/local/etc/profile.d/bash_completion.sh ]; then
	   . /opt/local/etc/profile.d/bash_completion.sh
fi

if [ -f ~/git-completion.bash ]; then
  . ~/git-completion.bash
fi

if [ -f ~/.bash_prompt ]; then
	. ~/.bash_prompt
fi

if [ -f ~/.bash_aliases ]; then
	source ~/.bash_aliases
fi
