#!/bin/bash - 

DOTFILES_ROOT=~/dotfiles
BASHCONFIG_ROOT=$DOTFILES_ROOT/config_bash

if [[ ! -f ~/.bash_profile ]]; then
	touch ~/.bash_profile
	echo ". ~/.bashrc" >> ~/.bash_profile
fi

ln -sf $BASHCONFIG_ROOT/bashrc ~/.bashrc
ln -sf $BASHCONFIG_ROOT/bash_alias.sh ~/.bash_alias.sh
ln -sf $BASHCONFIG_ROOT/bash_utils.sh ~/.bash_utils.sh
ln -sf $BASHCONFIG_ROOT/bash_prompt.sh ~/.bash_prompt.sh
ln -sf $BASHCONFIG_ROOT/git-prompt.sh ~/.git-prompt.sh

. ~/.bash_profile
