#!/bin/bash - 

ZSHCONFIG_ROOT=$DOTFILES_ROOT/config_zsh

if [[ ! -d  ~/.oh-my-zsh ]]; then
	git clone https://github.com/robbyrussell/oh-my-zsh.git ~/.oh-my-zsh
fi

if [[ ! -f ~/.zprofile ]]; then
	touch ~/.zprofile
	echo ". ~/.zshrc" >> ~/.zprofile
fi

ln -sf $ZSHCONFIG_ROOT/zshrc ~/.zshrc
if [[ ! -L ~/.zsh_custom ]]; then 
	ln -sf $ZSHCONFIG_ROOT/zsh_custom ~/.zsh_custom
fi
ln -sf $ZSHCONFIG_ROOT/zsh_alias.zsh ~/.zsh_alias.zsh

cat <<EOF
1. you need zshmarks plugin
 git clone https://github.com/jocelynmallon/zshmarks.git ~/.zsh_custom/plugins/

2. you need fzf-zshmarks
 git clone https://github.com/urbainvaes/fzf-marks.git ~/.zsh_custom/plugins/fzf-marks

EOF

