#!/bin/bash - 
#===============================================================================
#
#          FILE: deploy_ack.sh
# 
#         USAGE: ./deploy_ack.sh 
# 
#   DESCRIPTION: 
# 
#       OPTIONS: ---
#  REQUIREMENTS: ---
#          BUGS: ---
#         NOTES: ---
#        AUTHOR: dingmingxin (dmx), dignmingxin20@gmail.com
#  ORGANIZATION: 
#       CREATED: 11/03/2014 19:38
#      REVISION:  ---
#===============================================================================

ln -isf ~/dotfiles/config_ack/ackrc ~/.ackrc

