#!/bin/bash

rm ~/.tmux.conf
ln -s $TMUX_CON_ROOT/tmux.conf ~/.tmux.conf
if [[ ! -d ~/.tmuxinator ]]; then
	mkdir ~/.tmuxinator
else
	rm -r ~/.tmuxinator/*
fi

ln -s $TMUX_CON_ROOT/tmuxinator/* ~/.tmuxinator/
