#!/bin/bash

rm ~/.tmux.conf
rm ~/.tmux.conf.local
ln -s $TMUX_CON_ROOT/tmux.conf_1 ~/.tmux.conf
ln -s $TMUX_CON_ROOT/tmux.conf.local ~/.tmux.conf.local
if [[ ! -d ~/.tmuxinator ]]; then
	mkdir ~/.tmuxinator
else
	rm -r ~/.tmuxinator/*
fi

ln -s $TMUX_CON_ROOT/tmuxinator/* ~/.tmuxinator/
