#!/bin/bash - 
root=$DOTFILES_ROOT
ln -sif $root/config_emacs/init.el ~/.emacs.d/init.el
if [[ ! -L ~/.emacs.d/config ]]; then
	ln -sif $root/config_emacs/config ~/.emacs.d/config
fi
if [[ ! -L ~/.emacs.d/el-get-user ]]; then
	ln -sif $root/config_emacs/el-get-user ~/.emacs.d/el-get-user
fi
if [[ ! -L ~/.emacs.d/self_install ]]; then
	ln -sif $root/config_emacs/self_install ~/.emacs.d/self_install
fi
if [[ ! -L ~/.emacs.d/themes ]]; then
	ln -sif $root/config_emacs/themes ~/.emacs.d/themes
fi
