#!/bin/bash - 
#===============================================================================
#
#          FILE: deploy.sh
# 
#         USAGE: ./deploy.sh 
# 
#   DESCRIPTION: 下载vundle 部署vim
# 
#       OPTIONS: ---
#  REQUIREMENTS: ---
#          BUGS: ---
#         NOTES: ---
#        AUTHOR: 丁明信
#  ORGANIZATION: 
#       CREATED: 03/28/2014 10:17
#      REVISION:  ---
#===============================================================================

DOTFILES_ROOT=~/dotfiles
VIMFILES_DIR=$DOTFILES_ROOT/config_vim

addvundle()
{
	#git clone https://github.com/gmarik/vundle.git ~/.vim/bundle/vundle
	if [[ ! -d ~/.vim/bundle/Vundle.vim ]]; then
		git clone https://github.com/gmarik/Vundle.vim.git ~/.vim/bundle/Vundle.vim
	fi
}

dp_vimrc()
{
	step=$1
	if [[ $# -lt 0 ]]; then
		return
	fi
	if [[ $step -eq 1 ]]; then
		rm ~/.vimrc
		sed -n "1,/dingmingxin-base/p" $VIMFILES_DIR/vimrc >> ~/.vimrc
	else
		rm ~/.vimrc
		ln -sif $VIMFILES_DIR/vimrc ~/.vimrc
	fi
}

update_snippets()
{
	cp $VIMFILES_DIR/snippets/* ~/.vim/bundle/snipMate/snippets/
}

install_vim()
{
	addvundle
	dp_vimrc 1
	#自动安装插件
	vim +PluginInstall +qall
	#部署snippets
	update_snippets
	dp_vimrc 2
}

update_vimrc()
{
	dp_vimrc 1
	dp_vimrc 2
}

deploy()
{
	if [[ $# -eq 0 ]]; then
		install_vim 
		return
	fi
	mod=$1
	if [[ $mod = "snippets" ]]; then
		update_snippets
	elif [[ $mod = "vimrc" ]]; then
		update_vimrc
	fi
}

deploy $@
