#!/bin/bash - 
#===============================================================================
#
#          FILE: deploy_git.sh
# 
#         USAGE: ./deploy_git.sh 
# 
#   DESCRIPTION: 
# 
#       OPTIONS: ---
#  REQUIREMENTS: ---
#          BUGS: ---
#         NOTES: ---
#        AUTHOR: YOUR NAME (), 
#  ORGANIZATION: 
#       CREATED: 12/24/2014 11:17
#      REVISION:  ---
#===============================================================================

#use vimdiff compare file changes
#用法：git d filename
# git config --global diff.tool vimdiff
# git config --global diff.tool opendiff # using os x filemerge # 
# git config --global merge.tool opendiff # resolve confilict using osx filemerge # 
# git config --global difftool.prompt false       # 
# git config --global alias.d difftool            # 
# #diff colo setting                              # 
# git config --global color.diff auto             # 
# 
# #快捷映射                                       # 
# git config --global alias.co checkout           # 
# git config --global alias.st status             # 
# git config --global alias.ci 'commit -a'        # 
# git config --global alias.mg mergetool          # 
# 
# git config --global user.name "dingmingxin"     # 
# git config --global user.email dingmingxin20@gmail.com # 
# 
# #设置diff 使用的tabstop                         # 
# #git diff filename 时，起作用                   # 
# git config --global core.pager 'less -x4'       # 
ln -sif ~/dotfiles/config_git/gitconfig ~/.gitconfig

